name: Deploy (manual)

on:
  workflow_dispatch: {}

jobs:
  info:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Deployment instructions
      run: |
        echo "This workflow is intentionally manual and informational."
        echo "It will NOT perform SSH or run deploy scripts automatically."
        echo "To deploy, SSH to your server and run the commands in deploy/README.md or use the manual steps below:" 
        echo "  cd /var/www/news && git fetch origin main && git reset --hard origin/main && sudo systemctl restart news.service"
        echo "If you want Actions to perform deployment, re-enable the original deploy steps and add the necessary secrets (EC2_HOST, EC2_USER, EC2_PORT, EC2_SSH_KEY)."
